"""baseline schema

Revision ID: 6edc2e434e31
Revises: 
Create Date: 2026-08-18 11:43:10.976062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edc2e434e31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('SEM_CONTATO', 'QUEDA_UTILIZACAO', 'MUDANCA_HEALTH_SCORE', 'SATISFACAO_NEGATIVA', 'RENOVACAO_PROXIMA', 'RENOVACAO_RISCO', 'IMPLANTACAO_ATRASADA', 'RISCO_CRITICO', name='alerteventtype'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_create_task', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('done_by_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_score_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', name='indicatorsource'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'CS', 'GESTOR_CS', 'COMERCIAL', 'PROJETOS', 'SUPORTE', 'PRODUTO', 'GESTAO', name='rolename'), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('restricted_fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'resource', name='uq_permission_role_resource')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tier_cadences',
    sa.Column('tier', sa.Enum('PLATINA', 'OURO', 'PRATA', 'BRONZE', name='tierlevel'), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tier')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'CS', 'GESTOR_CS', 'COMERCIAL', 'PROJETOS', 'SUPORTE', 'PRODUTO', 'GESTAO', name='rolename'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corporate_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=120), nullable=True),
    sa.Column('economic_group', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('relationship_start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PROSPECT', 'EM_ONBOARDING', 'ATIVO', 'EM_RISCO', 'EM_RECUPERACAO', 'EM_RENOVACAO', 'CHURN', 'ENCERRADO', name='clientstatus'), nullable=False),
    sa.Column('tier', sa.Enum('PLATINA', 'OURO', 'PRATA', 'BRONZE', name='tierlevel'), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_template_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'CONCLUIDO', name='actionplanstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adoption_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('achieved_at', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_ins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('client_perception', sa.Text(), nullable=True),
    sa.Column('problems', sa.Text(), nullable=True),
    sa.Column('opportunities', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('commitments', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('contracted_at', sa.Date(), nullable=True),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.Column('usage_level', sa.Enum('NAO_AVALIADO', 'BAIXA', 'MEDIA', 'ALTA', name='usagelevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'module_id', name='uq_client_module')
    )
    op.create_table('client_owner_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('previous_owner_id', sa.String(length=36), nullable=True),
    sa.Column('new_owner_id', sa.String(length=36), nullable=True),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('contracted_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NAO_INICIADO', 'EM_IMPLANTACAO', 'IMPLANTADO', 'ATIVO', 'SUSPENSO', 'ENCERRADO', name='productstatus'), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'product_id', name='uq_client_product')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='contactstatus'), nullable=False),
    sa.Column('influence_level', sa.Enum('BAIXO', 'MEDIO', 'ALTO', name='influencelevel'), nullable=False),
    sa.Column('stakeholder_type', sa.Enum('SPONSOR', 'DECISOR', 'USUARIO', 'INFLUENCIADOR', 'TI', 'ADMINISTRATIVO', 'FINANCEIRO', 'OUTRO', name='stakeholdertype'), nullable=False),
    sa.Column('is_main_sponsor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_phase_participations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.Enum('HANDOFF', 'KICKOFF', 'PRE_GO_LIVE', 'GO_LIVE', 'HYPERCARE', name='implementationphase'), nullable=False),
    sa.Column('participated', sa.Boolean(), nullable=False),
    sa.Column('participation_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'phase', name='uq_cs_participation_client_phase')
    )
    op.create_table('expansion_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('module_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('CROSS_SELL', 'UPSELL', name='expansiontype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('stage', sa.Enum('IDENTIFICADA', 'EM_QUALIFICACAO', 'PROPOSTA', 'NEGOCIACAO', 'GANHA', 'PERDIDA', name='expansionstage'), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_score_manual_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('indicator_key', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_score_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classification', sa.Enum('VERDE', 'AMARELO', 'VERMELHO', name='healthscoreclassification'), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('calculated_by_id', sa.String(length=36), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('RISCO', 'IMPEDIMENTO', 'DEPENDENCIA', 'DECISAO', name='implementationeventtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementation_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementation_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NAO_INICIADO', 'PLANEJADO', 'EM_IMPLANTACAO', 'PRE_GO_LIVE', 'GO_LIVE', 'HYPERCARE', 'CONCLUIDO', name='implementationstatus'), nullable=False),
    sa.Column('situation', sa.Enum('NO_PRAZO', 'EM_ATENCAO', 'ATRASADO', name='implementationsituation'), nullable=False),
    sa.Column('expected_deadline', sa.Date(), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('journey_risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('EXPECTATIVA', 'RELACIONAMENTO', 'ADOCAO', 'SATISFACAO', 'RESULTADO_ESPERADO', name='journeyriskcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_journeys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('first_usage_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('post_go_live_objectives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_achieved', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renewals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=False),
    sa.Column('renewal_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_NEGOCIACAO', 'RENOVADO', 'NAO_RENOVADO', name='renewalstatus'), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='ticketseverity'), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'RESOLVIDO', 'FECHADO', name='ticketstatus'), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('ADOCAO', 'RELACIONAMENTO', 'PRODUTO', 'SUPORTE', 'IMPLANTACAO', 'FINANCEIRO', 'RENOVACAO', 'CONCORRENCIA', name='riskcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Enum('BAIXO', 'MEDIO', 'ALTO', name='riskimpact'), nullable=False),
    sa.Column('probability', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='riskprobability'), nullable=False),
    sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'MITIGADO', 'ENCERRADO', name='riskstatus'), nullable=False),
    sa.Column('action_plan_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('churn_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('renewal_id', sa.String(length=36), nullable=True),
    sa.Column('churn_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('PRECO', 'PRODUTO', 'SUPORTE', 'CONCORRENCIA', 'ORCAMENTO_CLIENTE', 'INSATISFACAO', 'OUTRO', name='churncategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lost_value', sa.Float(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['renewal_id'], ['renewals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_handoffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contracted_scope', sa.Text(), nullable=True),
    sa.Column('delivered_scope', sa.Text(), nullable=True),
    sa.Column('pending_items', sa.Text(), nullable=True),
    sa.Column('customizations', sa.Text(), nullable=True),
    sa.Column('integrations', sa.Text(), nullable=True),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('known_issues', sa.Text(), nullable=True),
    sa.Column('sponsor_contact_id', sa.String(length=36), nullable=True),
    sa.Column('stakeholders_notes', sa.Text(), nullable=True),
    sa.Column('business_objective', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('go_live_date', sa.Date(), nullable=True),
    sa.Column('hypercare_start', sa.Date(), nullable=True),
    sa.Column('hypercare_end', sa.Date(), nullable=True),
    sa.Column('next_adoption_steps', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['sponsor_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('REUNIAO', 'LIGACAO', 'EMAIL', 'CONTATO', 'RECLAMACAO', 'ELOGIO', 'DECISAO', 'COMPROMISSO', 'FEEDBACK', 'INCIDENTE', name='interactiontype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('module_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('module_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.Enum('MELHORIA', 'BUG', 'NOVA_FUNCIONALIDADE', 'ELOGIO', 'RECLAMACAO', name='feedbackcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NOVO', 'EM_ANALISE', 'PLANEJADO', 'ENTREGUE', 'RECUSADO', name='feedbackstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbrs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AGENDADO', 'REALIZADO', 'CANCELADO', name='qbrstatus'), nullable=False),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('next_period_goals', sa.Text(), nullable=True),
    sa.Column('action_plan_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_handoffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contract_reference', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('products_summary', sa.Text(), nullable=True),
    sa.Column('modules_summary', sa.Text(), nullable=True),
    sa.Column('customizations', sa.Text(), nullable=True),
    sa.Column('integrations', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('purchase_reason', sa.Text(), nullable=True),
    sa.Column('problem_to_solve', sa.Text(), nullable=True),
    sa.Column('contracting_objective', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('expected_deadline', sa.String(length=120), nullable=True),
    sa.Column('sponsor_contact_id', sa.String(length=36), nullable=True),
    sa.Column('stakeholders_notes', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('perceived_risks', sa.Text(), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('handoff_date', sa.Date(), nullable=True),
    sa.Column('pending_items', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['sponsor_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('NPS', 'CSAT', name='surveytype'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=False),
    sa.Column('respondent_contact_id', sa.String(length=36), nullable=True),
    sa.Column('respondent_name', sa.String(length=150), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['respondent_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='taskpriority'), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('action_plan_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', name='taskstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['account_risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_evidences')
    op.drop_table('tasks')
    op.drop_table('surveys')
    op.drop_table('sales_handoffs')
    op.drop_table('qbrs')
    op.drop_table('product_feedback')
    op.drop_table('interactions')
    op.drop_table('delivery_handoffs')
    op.drop_table('churn_records')
    op.drop_table('account_risks')
    op.drop_table('support_tickets')
    op.drop_table('renewals')
    op.drop_table('post_go_live_objectives')
    op.drop_table('onboarding_journeys')
    op.drop_table('onboarding_activities')
    op.drop_table('journey_risks')
    op.drop_table('implementation_summaries')
    op.drop_table('implementation_milestones')
    op.drop_table('implementation_events')
    op.drop_table('health_score_snapshots')
    op.drop_table('health_score_manual_values')
    op.drop_table('expansion_opportunities')
    op.drop_table('cs_phase_participations')
    op.drop_table('contacts')
    op.drop_table('client_products')
    op.drop_table('client_owner_history')
    op.drop_table('client_modules')
    op.drop_table('check_ins')
    op.drop_table('adoption_milestones')
    op.drop_table('action_plans')
    op.drop_table('onboarding_template_items')
    op.drop_table('modules')
    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tier_cadences')
    op.drop_table('products')
    op.drop_table('permissions')
    op.drop_table('health_score_indicators')
    op.drop_table('checklist_items')
    op.drop_table('audit_logs')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
